### ISSUE TITLE
Move to a subdomain

### ISSUE THREAD

**Issue by arkon** [unhaltable/txti#13]
Move everything from `www.unhaltable.com` to either `www.txti.unhaltable.com` or `www.unhaltable.com/txti`. Votes?

**Comment by elliottsj** [comment]
Just `txti.unhaltable.com`

**Comment by elliottsj** [comment]
Also, switch to CloudFlare for DNS. Maybe share the account since CloudFlare is free (i.e. no payment info is at risk)

**Comment by arkon** [comment]
NTS: set up main site for team, which would probably let all the projects be able to be accessed via subdirectories. Also move Cryptr sites to Github.
